spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_batch_demo
    username: spring_batch
    password: spring_batch

logging:
  level:
    root: DEBUG

